[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
ITensorGaussianMPS = "2be41995-7c9f-4653-b682-bfa4e7cebb93"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuantumToolbox = "6c2fb7c5-b903-41d2-bc5e-5a7c320b9fab"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"

[compat]
BenchmarkTools = "=1.6.3"
CairoMakie = "=0.15.8"
CUDA = "=5.9.5"
CUDA_Runtime_jll = "=0.19.2"
IJulia = "=1.33.0"
ITensorGaussianMPS = "=0.1.13"
ITensorMPS = "=0.3.26"
ITensors = "=0.9.15"
JLD2 = "=0.6.3"
OrdinaryDiffEq = "=6.105.0"
Plots = "=1.41.4"
QuantumToolbox = "=0.40.0"
Revise = "=3.13.1"
StochasticDiffEq = "=6.87.0"
